FROM python:3.10-slim

WORKDIR /app

ENV PYTHONPATH=/app

COPY pyproject.toml poetry.lock ./
RUN pip install poetry && poetry config virtualenvs.create false && poetry install --no-interaction --no-ansi

COPY ./src/containers/db_service/ /app/src/containers/db_service/

WORKDIR /app/src/containers/db_service

CMD ["alembic", "upgrade", "head"]
